drop index if exists public.idx_basketball_stats_session;
drop index if exists public.ux_basketball_session_stats_session;
drop index if exists public.idx_cardio_user_workout;
drop index if exists public.idx_exercise_sets_workout_exercise_id;
drop index if exists public.idx_follows_pairs;
alter table public.follows drop constraint if exists follows_uniq;
alter table public.follows drop constraint if exists follows_unique;
drop index if exists public.idx_football_stats_session;
drop index if exists public.ux_football_session_stats_session;
drop index if exists public.idx_messages_conv_id;
alter table public.profiles drop constraint if exists profiles_username_lower_key;
drop index if exists public.profiles_username_lower_uidx;
drop index if exists public.idx_racket_stats_session;
drop index if exists public.ux_racket_session_stats_session;
drop index if exists public.sport_sessions_sport_idx;
drop index if exists public.sport_sessions_started_idx;
drop index if exists public.sport_sessions_user_time_idx;
alter table public.user_achievements drop constraint if exists user_achievements_user_achievement_unique;
drop index if exists public.ux_user_achievements;
drop index if exists public.user_rankings_daily_day_idx;
drop index if exists public.ux_volleyball_session_stats_session;
alter table public.weekly_goal_results drop constraint if exists weekly_goal_results_goal_week_unique;
drop index if exists public.workout_exercises_workout_id_idx;
drop index if exists public.workout_likes_user_id_idx;
drop index if exists public.wp_workout_idx;
drop index if exists public.idx_workout_scores_workout_id_algo;
drop index if exists public.workouts_user_id_started_at_idx;
