default_platform(:ios)

platform :ios do
  desc "Compila y ejecuta tests"
  lane :ci do
    scan(
      scheme: ENV["APP_SCHEME"] || "Liftr",
      clean: true,
      devices: ["iPhone 16 Pro"]
      # Si aún no tienes tests, añade: skip_tests: true
    )
  end

  desc "Build + Upload a TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      duration: 1200,
      in_house: false
    )

    increment_build_number(xcodeproj: "Liftr.xcodeproj")

    build_app(
      scheme: ENV["APP_SCHEME"] || "Liftr",
      export_method: "app-store",
      include_bitcode: false,
      include_symbols: true
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: false,
      groups: ["Internal Testers"]
    )
  end
end
