default_platform(:ios)

platform :ios do
  desc "Build + Upload to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      duration: 1200,
      in_house: false
    )

    increment_build_number(xcodeproj: "Liftr.xcodeproj")

    build_app(
      scheme: ENV["APP_SCHEME"] || "Liftr",
      export_method: "app-store"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end
end
